import { Metadata } from "next";
import AppProvider from "../contexts/appProvider";
import Dashboard from "../components/common/dashboard/dashboard";
export const metadata: Metadata = {
  title: "Personal Kanban App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Dashboard>
            {children}
          </Dashboard>
        </AppProvider>
      </body>
    </html>
  );
}
