name: Merge Latest Release to Release Branch

on:
  push:
    tags:
      - 'v*.*.*'  # Matches any version tag (e.g., v1.0.0)

jobs:
  merge-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git
        uses: actions/setup-git@v2
        with:
          email: "ethan.ekhtiyar@gmail.com"
          name: "GitHub Action"

      - name: Merge Latest Release Tag into Release Branch
        run: |
          git fetch --tags
          git checkout release
          git pull origin release
          git merge $GITHUB_REF --no-ff -m "Merging latest release tag into release branch"
          git push origin release
